#include "universe.h"

int UNIVERSE_SIZE = 512; 

int WINDOW_W = 800;
int WINDOW_H = 600;

int PRETEND_SCREEN_W = 256;
int PRETEND_SCREEN_H = 192;

vec2 CENTRE_SCREEN(PRETEND_SCREEN_W / 2, PRETEND_SCREEN_H / 2); 

